### PR TITLE
Return Values Calculated Fixed

### PR DESCRIPTION
**Pull request by ghost**
4 logical errors have been fixed in the Application CalculatorReturnValue

### CODE REVIEW

**Comment by aceware152** [comment]
Hey mate it’s been a long time since I did this course but from memory we are meant to clone the repository and then fork it so that we handle the pull request ourselves. 

If anyone is monitoring the master branch they won’t accept the pull request because then the next student won’t be able to solve the problem as well. Happy New Year

**Comment by ghost** [comment]
Hi,

Thanks for the advice received. So, to understand your correctly. I download/clone the OpenCollegesProgramming/CalculatorReturnValue to a local storage on my hard drive then import this into my GitHub repo and then fork this?

**Comment by aceware152** [comment]
You do it all on git hub. You create a your own repository and make it a clone of the calculator return repo, then you fork it fix the issue and merge it

**Comment by aceware152** [comment]
This is a link to the one I did for mine

https://github.com/aceware152/CalculatorReturnValue

If you have any dramas there is a face book group someone there will be able to help you out

E1161 Certificate IV In Programming. Open Colleges

I am one of the admins

**Comment by ghost** [comment]
Thanks for the link, much appreciated. I’ll give it a go and if I get stuck I’ll definitely asked the question.

Just one thing I’ve notice that when I clone the repo my local storage and then try to drag and drop all file. Having issues dropping the below

[cid:image001.png@01D5C26B.4664D480]


I have successfully managed to drop all of the below files except the 2 above.

[cid:image002.png@01D5C26B.5F2EA7C0]

**Comment by aceware152** [comment]
I don’t believe you need to create it on your local drive and I don’t really know why the files won’t copy

**Pull request closed without merging**
